### ISSUE TITLE
json decode error on "ctf challenge install"

### ISSUE THREAD

**Issue by mtverraen** [CTFd/ctfcli#31]
ctfcli is installed with pip and initialized. Then a new challenge is created with `ctf challenge new web` and given the name "Hello". On `ctf challenge install Hello` the following result appears:

```
Found Hello/challenge.yml
Loaded Hello
Traceback (most recent call last):
  File "/usr/local/bin/ctf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/ctfcli/__main__.py", line 74, in main
    fire.Fire(CTFCLI)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ctfcli/cli/challenges.py", line 94, in install
    installed_challenges = load_installed_challenges()
  File "/usr/local/lib/python3.8/site-packages/ctfcli/utils/challenge.py", line 28, in load_installed_challenges
    return s.get("/api/v1/challenges?view=admin", json=True).json()["data"]
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ColdHeat** [comment]
Does the access token you're using belong to an admin?

**Comment by mtverraen** [comment]
Yup. Tried with the "default"-admin from the initial setup of ctfd and a newly created admin account. Both gave the same stacktrace. I've tried building with python@3.8 and 3.9, but I don't think the python version is the culprit either?
