### ISSUE TITLE
Install challenge KeyError: 'data'

### ISSUE THREAD

**Issue by kraft87** [CTFd/ctfcli#85]
Getting the following error when trying to use ctfcli. This only began to happen once I upgraded to ctfd 3.4.1 and does not occur on ctfd 3.4.0.
```
Traceback (most recent call last):
  File "../../utils/ctf", line 11, in <module>
    load_entry_point('ctfcli==0.0.9', 'console_scripts', 'ctf')()
  File "/home/user/.local/lib/python3.8/site-packages/ctfcli/__main__.py", line 78, in main
    fire.Fire(CTFCLI)
  File "/home/user/.local/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/.local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/user/.local/lib/python3.8/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/ctfcli/cli/challenges.py", line 143, in install
    installed_challenges = load_installed_challenges()
  File "/home/user/.local/lib/python3.8/site-packages/ctfcli/utils/challenge.py", line 28, in load_installed_challenges
    return s.get("/api/v1/challenges?view=admin", json=True).json()["data"]
KeyError: 'data'
```

**Comment by diohabara** [comment]
@kraft87 I'm facing this issue. How did you solve it?
